AaronLasseigne/active_interaction

lib/active_interaction.rb, lib/active_interaction/base.rb, lib/active_interaction/concerns/active_recordable.rb, spec/active_interaction/base_spec.rb, spec/active_interaction/concerns/active_recordable_spec.rb
In #248 we're going to have to add another ActiveRecord method. It seems reasonable that we would group them like we do ActiveModel.
=> Split our ActiveRecord related methods

CHANGELOG.md, lib/active_interaction/concerns/active_recordable.rb, spec/active_interaction/concerns/active_recordable_spec.rb
=> Fix simple_form gem integration.

README.md
It seems like these should always return the same type of thing.
@tfausak please review
=> README controller interaction updates

README.md
=> Add documentation for #to_model

CHANGELOG.md, README.md
=> Link to announcement post in readme and change log

lib/active_interaction/backports.rb, spec/active_interaction/errors_spec.rb, spec/active_interaction/filters/hash_filter_spec.rb
The 99% coverage was bothering me. I want to get it back to 100%. The back ports are the only lines without coverage.
=> Increase code coverage

README.md
=> Update documentation to reference correct method

README.md
=> Add link to Aire from Rails section

README.md
=> Link to optional inputs from predicates

README.md
=> Add a section about grouped inputs

lib/active_interaction/locale/fr.yml
I'm french, I had to translate it.
I thought it might be a good idea to share my translations with the community
I didn't translate the types, nobody do that. lol.
=> Adding French localisation

README.md, example/app/interactions/things/create_thing.rb, example/app/interactions/things/update_thing.rb
=> Merge errors instead of records

active_interaction.gemspec
They don't appear to be necessary anymore.
=> Remove dependencies specific to Rubinius

.travis.yml, active_interaction.gemspec, gemfiles/activemodel-4.0.rb, gemfiles/activemodel-4.1.rb, gemfiles/activemodel-4.2.rb, gemfiles/activemodel-5.0.rb
=> add testing for activemodel through Rails 5.0.0.beta1

README.md
=> Bold the documentation about type checking and validation

README.md
This addresses the confusion raised in #367.
=> Add documentation about predicates for booleans

.travis.yml, active_interaction.gemspec, gemfiles/activemodel-5.0.rb
=> Fix the Travis CI build

lib/active_interaction/concerns/runnable.rb, lib/active_interaction/errors.rb, spec/active_interaction/concerns/runnable_spec.rb
=> throw an error to allow ActiveRecord transactions to roll back

.travis.yml
=> Try to fix the Rubinius build

README.md
=> Update README for integer filter with base option

README.md, example/app/interactions/things/update_thing.rb, lib/active_interaction/base.rb, spec/active_interaction/base_spec.rb
=> Gh 398 no predicates

lib/active_interaction/locale/it.yml
Hey! Great gem!
This is my little contribution :)
=> Add italian locale

README.md
https://github.com/AaronLasseigne/active_interaction/blob/master/lib/active_interaction/filters/string_filter.rb#L37
=> Fix string strip documentation

lib/active_interaction/locale/es.yml
Adds spanish locale.
I did not translate the types because I feel it's better this way, but open to translate it as well.
=> adds spanish locale

CHANGELOG.md, README.md
=> Minor readme fixes
