- lib/active_interaction/errors.rb
This pull request is in response to #255. When you define a hash with `default: {}`, we eagerly build the default value. If one of the inputs inside that hash doesn't have a default, you'll get an error. For example:
``` rb
hash :x, default: {} do
string :y
end
end
```
Since there's no error message, it's basically useless. This pull request adds a message to that error. Now it looks like this:
``` rb
hash :x, default: {} do
string :y
end
end
```
Can you review this, @AaronLasseigne?
> Improve invalid nested value error message

- lib/active_interaction/base.rb
- spec/active_interaction/concerns/active_recordable_spec.rb
- spec/active_interaction/integration/interface_interaction_spec.rb
- spec/active_interaction/integration/model_interaction_spec.rb
Fixes #263. 
``` rb
class InterfaceInteraction < ActiveInteraction::Base
interface :anything
def execute
anything
end
end
InterfaceInteraction.run!(anything: nil)
class ModelInteraction < ActiveInteraction::Base
model :object
def execute
object
end
end
ModelInteraction.run!(object: nil)
```
> Allow nil for interfaces and models

- CHANGELOG.md
- lib/active_interaction/base.rb
- spec/active_interaction/integration/array_interaction_spec.rb
- spec/active_interaction/integration/hash_interaction_spec.rb
Fixes #269. 
This pull request makes it so that defaults don't get eagerly evaluated if they're procs. Take this interaction for example:
``` rb
object :object,
default: -> { puts 'default'; Object.new }
end
```
Simply by defining this class, `"default"` will be output the standard out. That's a little surprising.
We eagerly evaluate defaults to make sure you didn't give us something that would never work. Since procs can change every time they are called, it doesn't make sense to eagerly evaluate them for this purpose.
> Don't eagerly evaluate proc defaults

- lib/active_interaction/backports.rb
- lib/active_interaction/filters/hash_filter.rb
I think we should not monkey patch classes outside of the ActiveInteraction module. This pull request removes the `Hash#transform_keys` monkey patch. It replaces it with a class method that delegates to `#transform_keys` if it is available. If it's not, it implements its own version.
> Don't monkey patch #transform_keys onto Hash

- CHANGELOG.md
- lib/active_interaction.rb
- lib/active_interaction/base.rb
- lib/active_interaction/concerns/transactable.rb
- lib/active_interaction/errors.rb
- lib/active_interaction/filters/array_filter.rb
- lib/active_interaction/filters/hash_filter.rb
- lib/active_interaction/filters/model_filter.rb
- lib/active_interaction/locale/en.yml
- lib/active_interaction/modules/validation.rb
- spec/active_interaction/errors_spec.rb
- spec/active_interaction/modules/validation_spec.rb
Fixes #277. This pull request deprecates methods that will be removed in version 2.0.0. 
- `ActiveInteraction::Base.model` has been removed and replaced with `.object`. This deprecates the former and makes the latter available.
- `ActiveInteraction::Base.transaction` has been removed. This deprecates it.
- `ActiveInteraction::Errors#add_sym` has been removed and obsoleted by `#add`. This deprecates the former and updates the latter.
Here is an example of an interaction that uses all of the deprecated features:
``` rb
require 'active_interaction'
class Outdated < ActiveInteraction::Base
model :anything, class: 'Object'
transaction false
def execute
errors.add_sym(:base)
end
end
Outdated.run
```
Running that with this pull request makes this output:
```
DEPRECATION WARNING: model is …
```
> Deprecate methods removed in v2.0.0

- CHANGELOG.md
- active_interaction.gemspec
- lib/active_interaction/filters/file_filter.rb
- spec/active_interaction/filters/file_filter_spec.rb
- spec/active_interaction/integration/file_interaction_spec.rb
Fixes #286. 
This pull request changes the method we check for on file inputs from `#eof?` to `#rewind`. The former is not available on uploaded files in Rails until version 4.0.2. I would prefer to use something more intention-revealing like `#to_io`, but that's not available until version 4.2. Since we support 3.2.0, we have to pick from the method available in that version. 
I also added a test case to make sure we don't accidentally break this again.
> Check for rewind instead of eof? on file inputs

- .rubocop.yml
- .travis.yml
- gemfiles/activemodel-3.2.rb
While working on #287, I realized that we are testing against the latest ActiveModel 3.2.x. Since we support 3.2.0, we should test against it instead.
> Test against activemodel 3.2.0

- lib/active_interaction.rb
- lib/active_interaction/base.rb
- lib/active_interaction/filters/array_filter.rb
- lib/active_interaction/filters/hash_filter.rb
This should have been removed in 2.0.0.
> Remove obsolete deprecate method

- README.md
- lib/active_interaction/base.rb
- spec/active_interaction/base_spec.rb
Fixes #294. This pull request adds a new `#given?` method to interactions that checks for optional inputs. It allows users to check for the difference between an input being given as `nil` and an input not being given at all. For example:
``` rb
integer :x, :y,
default: nil
def execute
[given?(:x), given?(:y)]
end
end
Example.run!(y: nil)
```
Still to do:
> Add method to check for optional inputs

- CHANGELOG.md
- lib/active_interaction/base.rb
- spec/support/interactions.rb
This pull request fixes #296. It more or less reverts part of e52dd8b1b6386e89665830a65d1e8a267155411c that proved unnecessary (and in fact harmful) after e50bc2bac3f52fbe4d4224ada085497fa606cd01. 
Can you review this, @AaronLasseigne?
> Raise InvalidDefaultError instead of silently converting to nil

- CHANGELOG.md
- lib/active_interaction/errors.rb
- spec/active_interaction/integration/array_interaction_spec.rb
- spec/active_interaction/integration/hash_interaction_spec.rb
This pull request fixes #298. It makes `InvalidNestedValueError` a subclass of `InvalidValueError`. This seemed like the best way to fix the issue. I can't imagine there are any situations where you'd want to catch an invalid value error but ignore invalid nested value errors.
@AaronLasseigne can you review this?
> Fix #298; don't raise exceptions for invalid nested values

- lib/active_interaction/filters/object_filter.rb
This pull request is in response to #302. It changes the `InvalidClassError` message. If you define an object filter for a class that doesn't exist, the message can be confusing. 
``` rb
object :cow
end
Example.run
```
The class is invalid to ActiveInteraction because it doesn't exist. The new error message is hopefully better.
``` rb
Example.run
```
> Improve error message for invalid classes

- CHANGELOG.md
- lib/active_interaction/filter.rb
- spec/active_interaction/integration/hash_interaction_spec.rb
This pull request changes the error message when you have an invalid nested default. Its goal is to make it clearer what the problem is. Issue #309 may have been avoided if something like this was in place. 
Here is an example of the new message:
``` rb
hash :h,
default: {} do
boolean :b
end
end
```
> Give better error message for invalid nested defaults

- .rubocop.yml
- CHANGELOG.md
- lib/active_interaction/base.rb
- spec/active_interaction/base_spec.rb
This pull request makes it so that you get a warning when you redefine a filter. Issue #308 brought the need for this to my attention. 
Here is an example of the warning:
``` rb
boolean :x, :x
end
```
> Warn when redefining a filter

- lib/active_interaction/filters/array_filter.rb
This pull request fixes #320. It avoids requiring ActiveRecord. This is necessary because other gems use the existence of ActiveRecord to do other things. In #320, for example, rspec-rails tries to use the not-configured database because it thinks we're using ActiveRecord.
I think this is a safe change to make because we only refer to ActiveRecord at runtime in `ActiveInteraction::ArrayFilter#classes`. If you want to pass an ActiveRecord collection to an array filter, obviously you have already loaded ActiveRecord.
> Don't require Active Record

- lib/active_interaction/concerns/runnable.rb
- lib/active_interaction/errors.rb
There's no need for a full on error object here. Ruby has throw/catch to handle this and it help distinguish errors that might reach the end user from what is otherwise an internal signal.
> switch internal only error to a throw/catch

- .travis.yml
This pull request tries to configure Travis CI to use JRuby 9000 instead of JRuby 1.7. See #344 for details.
> JRuby 9000

- .travis.yml
- active_interaction.gemspec
- lib/active_interaction/backports.rb
> Drop support for Ruby 1.9.3

- .travis.yml
- README.md
- active_interaction.gemspec
- gemfiles/activemodel-3.2.rb
- lib/active_interaction/backports.rb
- spec/active_interaction/filters/hash_filter_spec.rb
> Drop support for ActiveModel 3.2

- README.md
- lib/active_interaction/concerns/runnable.rb
- lib/active_interaction/errors.rb
- spec/active_interaction/base_spec.rb
> Copy symbolic errors when composing

- .rubocop.yml
- active_interaction.gemspec
- benchmarks/filters.rb
- lib/active_interaction/base.rb
- lib/active_interaction/filter.rb
- lib/active_interaction/filters/abstract_date_time_filter.rb
- lib/active_interaction/filters/abstract_numeric_filter.rb
- lib/active_interaction/filters/time_filter.rb
- spec/active_interaction/base_spec.rb
- spec/active_interaction/concerns/runnable_spec.rb
- spec/active_interaction/filters/date_filter_spec.rb
- spec/active_interaction/filters/date_time_filter_spec.rb
- spec/active_interaction/filters/decimal_filter_spec.rb
- spec/active_interaction/filters/hash_filter_spec.rb
- spec/active_interaction/filters/object_filter_spec.rb
- spec/active_interaction/filters/string_filter_spec.rb
- spec/active_interaction/filters/time_filter_spec.rb
- spec/active_interaction/integration/array_interaction_spec.rb
- spec/active_interaction/integration/hash_interaction_spec.rb
- spec/active_interaction/integration/time_interaction_spec.rb
- spec/support/filters.rb
- spec/support/interactions.rb
This pul request updates us to [RuboCop 0.36.0](https://github.com/bbatsov/rubocop/releases/tag/v0.36.0). It also changes the version specification from `~> 0.35` to `~> 0.36.0`. This should prevent the build from breaking when 0.37 comes out. 
I left one cop failing:
```
lib/active_interaction/filter.rb:17:15: C: Style/MutableConstant: Freeze mutable objects assigned to constants.
CLASSES = {}
^^
```
There are a variety of ways we could fix this one. Or we could ignore the cop here. Not sure what to do.
@AaronLasseigne can you review this?
> Upgrade to RuboCop 0.36

- lib/active_interaction/errors.rb
- spec/active_interaction/errors_spec.rb
This only occurs when errors that are strings are added to `:base` and then composed into another interaction.
fixes #349
> Do not translate error strings on :base when merging errors.

- lib/active_interaction/filter.rb
- spec/support/filters.rb
This fixes #357. It changes the default lambda to allow taking a filter argument. If the lambda has arity 0 (that is, it takes no arguments), it will continue to work as before. If it has arity 1, it will be passed the filter that it is a default for.
``` rb
boolean :x, default: -> { false }
boolean :y, default: -> (filter) { p filter.name; true }
```
> Allow default lambdas to take a filter argument

- lib/active_interaction/locale/pt-BR.yml
- spec/active_interaction/i18n_spec.rb
- spec/spec_helper.rb
- Cloned en.yml file and translated available keys (except for the "types" collection)
- Change the test "contains localization file paths..." to now get the 2nd file in the
path, because the pt-BR file appears before (I guess it's because of the dash and upper
letters)
- Duplicated the english translation test and switched the context to brazilian portuguese
- Added the pt-BR language to the available locales in spec_helper.rb
If anything is missing, please, ping me and I'll fix it.
I didn't translated the types collection, to match the fr.yml translation.
> Creating translation for pt-BR language

- lib/active_interaction/concerns/runnable.rb
- spec/active_interaction/concerns/runnable_spec.rb
Before this change, if a composed interaction failed, neither around nor after callbacks would be yielded to.
> Allow callbacks to interact with failures from composed interactions

- lib/active_interaction/filters/boolean_filter.rb
- spec/active_interaction/filters/boolean_filter_spec.rb
Sometimes used in other libraries (eg. polymer)
> Update boolean_filter : on/off support

- lib/active_interaction/base.rb
- lib/active_interaction/modules/input_processor.rb
- spec/active_interaction/modules/input_processor_spec.rb
> Throw an error for all reserved input names.

- lib/active_interaction/base.rb
- spec/active_interaction/base_spec.rb
> Allow ActionController::Parameters as inputs

- lib/active_interaction/filters/integer_filter.rb
- spec/active_interaction/filters/integer_filter_spec.rb
> Add a base option to integer filters

- README.md
- lib/active_interaction/base.rb
- spec/active_interaction/base_spec.rb
closes #408
After some thought, I don't think `given?` should work on arrays. The goal of `given?` is to determine whether an optional input was passed. With arrays we don't have optional entries in the array.
> make given? capable of checking hash filter keys too

- README.md
- lib/active_interaction/filters/integer_filter.rb
- spec/active_interaction/filters/integer_filter_spec.rb
closes #392 
This only applies the `:base` option to strings that are being converted.
> default the integer base to 10

- lib/active_interaction/filters/decimal_filter.rb
Ruby 2.6 throws a deprecation warning using `BigDecimal.new` instead of `BigDecimal()`.
> Updated decimal filter to new ruby 2.6+ BigDecimal initialization format

- README.md
The source code for the Interface Filter has an example where you don't have to supply any methods to it if you want to allow _anything_ in your interaction. This PR adds a similar example to the Readme to keep it consistent.
> Add Note in Readme about Interface not requiring methods

- README.md
- lib/active_interaction/concerns/runnable.rb
- lib/active_interaction/errors.rb
- spec/active_interaction/concerns/runnable_spec.rb
Allows an `ActiveInteraction::InvalidInteractionError` to behave in a similar way as `ActiveRecord::RecordInvalid` which exposes the failed `#record`.
`ActiveInteraction::InvalidInteractionError` exposes `#interaction` attribute which includes failing interaction. This feature allows for better inspection of why interaction failed and therefore makes feedback to consumers of interaction errors more flexible.
Take for example a Rails controller action which might need to be rescued and whose error details need to be passed to the frontend.
```ruby
class FooController < ApplicationController
rescue_from ActiveInteraction::InvalidInteractionError do |exception|
render json: { errors: exception.interaction.errors.details }, status: :unprocessable_entity
end
def update
result = …
```
> Pass instance of the interaction to InvalidInteractionError class

- lib/active_interaction/concerns/runnable.rb
- spec/active_interaction/concerns/runnable_spec.rb
> Fix errors on callbacks #486

- .travis.yml
- gemfiles/activemodel-6.1.rb
- lib/active_interaction/backports.rb
- lib/active_interaction/errors.rb
- spec/active_interaction/errors_spec.rb
* only includes Backports error details code when using ActiveModel < 5
* fixes spec to adhere to Rails 6.1
Closes #488 #489 #490
> Add support Rails 6.1

- lib/active_interaction/errors.rb
Rails 5 introduced `details` method, and we have branches to support Rails before and after this feature.
Since now we only support >5, we can remove Rails 4.x support code (before `details` was introduced).
> Remove ActiveModel errors support prior to Rails 5

- CHANGELOG.md
- README.md
In ActiveModel version 5.2 or later, passing a string to the if: and unless: options raises ArgumentError.
```
ArgumentError: Passing string to be evaluated in :if and :unless conditional options is not supported.
Pass a symbol for an instance method, or a lambda, proc or block, instead.
```
https://github.com/rails/rails/blob/main/activesupport/lib/active_support/callbacks.rb#L356
This PR replaces string passed to :unless option of validate methods in README with proc.
Could you please have a moment to take a look at it? @AaronLasseigne
> Replace string passed to :unless with proc

- spec/active_interaction/base_spec.rb
Hi! I planned to contribute but I got error running the tests out of the box.
This PR fix errors I had:
```
rspec ./spec/active_interaction/base_spec.rb:224 # ActiveInteraction::Base with a filter .run(inputs = {}) passing validations failing runtime validations returns an invalid outcome
rspec ./spec/active_interaction/base_spec.rb:232 # ActiveInteraction::Base with a filter .run(inputs = {}) passing validations failing runtime validations has errors
rspec ./spec/active_interaction/base_spec.rb:239 # ActiveInteraction::Base with a filter .run(inputs = {}) passing validations failing runtime validations has detailed errors
rspec ./spec/active_interaction/base_spec.rb:228 # ActiveInteraction::Base with a filter .run(inputs = {}) passing validations failing runtime validations sets the …
```
> TEST: Fix error "undefined method `silence_warnings'"

- lib/active_interaction/inputs.rb
- spec/active_interaction/base_spec.rb
- spec/active_interaction/inputs_spec.rb
While upgrading to active interaction `5.0.0` I found that the `inputs must be a hash or ActionController::Parameters` argument error is being raised when inputs are composed within an interaction (i.e. `compose(Multiply, inputs)` ). It looks like that error will be raised unless they are a hash or an `ActionController::Parameters` instance when we probably want to also allow them to be `Inputs` for composition. 
I wrote two test cases, one for the `#normalized` method where the error gets raised to make sure it does not when they are of type `ActiveInteraction::Inputs` and one for the `#compose` method directly to ensure it is a valid outcome for both a hash or an `Inputs` instance.
It's my first time reading through the library source, so if I'm missing anything obvious or there is a …
> Fix compose inputs

- lib/active_interaction/filters/array_filter.rb
- spec/active_interaction/filters/array_filter_spec.rb
Addresses #545 
Description has most of the detail: simply replace the `map!` call in `ArrayFilter#process` to reassign and use `map`.
I only added a test for the `ArrayFilter` class but happy to add a more comprehensive integration test.
Happy for any feedback!
> Use a non-destructive `map` call when transforming an Array filter

- lib/active_interaction/base.rb
- spec/active_interaction/integration/boolean_interaction_spec.rb
It would be nice to be able to use a boolean filter like `<filter_name>?` instead of `<filter_name>`.
> Provide more fluent interface to handle boolean filter

- lib/active_interaction/locale/ko.yml
- spec/active_interaction/i18n_spec.rb
I think it's much nice if we have ko locale.
> Add ko locale

- .github/workflows/test.yml
- gemfiles/rails-7.1.gemfile
I added Ruby 3.3 and Rails 7.1 for testing.
Ruby 3.3.0 has a few regressions so I still keep ruby 3.2 in the matrix in the CI.
> Test active_interaction on ruby 3.3 and rails 7.1
